name: Build Design system Lib

on:
  workflow_call:

# Change the working directory for all the jobs in this workflow
defaults:
  run:
    working-directory: packages/design-system

jobs:
  build-design-system:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
      # Setup node with version 16.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      
      # set git config
      - name: Set git config to github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
     
     # Run yarn install to install project packages
      - name: Yarn
        run: yarn install --frozen-lockfile
      
      # yarn build to build the project
      - name: Build package
        run: yarn build
      
      #- name: Run Storybook tests
      #  run: yarn test-storybook:ci
      
      - name: Run Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
        
      #- name: Run and publish to Chromatic
      #  uses: chromaui/action@v1
      #  # Chromatic GitHub Action options
      #  with:
      #    # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
      #    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}  
